# Generated by Django 5.2.1 on 2025-05-15 05:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1), ('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Link text', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Destination URL', 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('url', 3)]], {})}),
        ),
    ]
