# Generated by Django 5.2.1 on 2025-05-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articleindexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': 'Article Page'},
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='date_published',
            field=models.DateField(verbose_name='Date Published'),
        ),
        migrations.DeleteModel(
            name='ArticleIndexPage',
        ),
    ]
