# Generated by Django 5.2.1 on 2025-05-15 06:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Ad'), ('audio', 'Audio Ad')], max_length=10)),
                ('target_url', models.URLField(help_text='Where the user will be redirected on click.')),
                ('audio_file', models.FileField(blank=True, help_text='Only required for audio ads.', null=True, upload_to='ads/audio/')),
                ('caption', wagtail.fields.RichTextField(blank=True, help_text='Optional description or call-to-action.')),
                ('image', models.ForeignKey(blank=True, help_text='Only required for banner ads.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
