# Generated by Django 5.2.1 on 2025-05-15 15:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_delete_advertisementpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, help_text='Only required for banner ads.', null=True),
        ),
    ]
