# Generated by Django 5.2.1 on 2025-05-15 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisodepage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])]),
        ),
    ]
